In [1]:
python --version

NameError: name 'python' is not defined

In [2]:
!python --version

Python 3.12.3


In [3]:
import numpy as np
print(np.__version__)

2.2.3


In [11]:
arry = np.arange(12).reshape(3,4)
print(arry)
print("\n",arry.T)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


## sort the array column wise using axis = 0

In [29]:
a2d_arry = np.array([[1,4,3],
                     [4,6,10],
                     [2,2,5]])
a2d_arry.sort(axis=0)
print(a2d_arry)

[[ 1  2  3]
 [ 2  4  5]
 [ 4  6 10]]


## sort the array row wise using axis = 1

In [30]:
a2d_arry = np.array([[1,4,3],
                     [4,9,6],
                     [7,2,5]])
a2d_arry.sort(axis=1)
print(a2d_arry)

[[1 3 4]
 [4 6 9]
 [2 5 7]]


## mask 
